jobs:
  build:
    name: Build docker images
    runs-on: ubuntu-latest

    on:
      push:
        branches:
        - master
      pull_request
      schedule:
      - cron:  '* * * * *'
        branches:
        - master

    steps:
    - uses: actions/checkout@master
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

  publish:
    name: Publish docker images
    runs-on: ubuntu-latest

    on:
      push:
        branches:
        - master
      schedule:
      - cron:  '* * * * *'
        branches:
        - master

    steps:
    - uses: actions/checkout@master
    - name: Run a multi-line script
      run: |
        echo This is a schedule test
